[project]
name = "tripwallet"
version = "0.2.0"
description = "A lightweight trip-based expense sharing app"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "email-validator==2.2.0",
    "fastapi==0.116.1",
    "pyjwt==2.10.1",
    "uvicorn[standard]==0.35.0",
]

[dependency-groups]
dev = [
    "httpx==0.28.1",
    "pytest==8.4.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
